// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-assessments.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var ASSESSMENTS = [
  { id: "holland", name: "\u05E7\u05D5\u05D3 \u05D4\u05D5\u05DC\u05E0\u05D3", description: "\u05D4\u05E2\u05D3\u05E4\u05D5\u05EA \u05EA\u05E2\u05E1\u05D5\u05E7\u05EA\u05D9\u05D5\u05EA \u05DC\u05E4\u05D9 6 \u05D8\u05D9\u05E4\u05D5\u05E1\u05D9\u05DD (RIASEC)." },
  { id: "via", name: "VIA \u2014 \u05D7\u05D5\u05D6\u05E7\u05D5\u05EA \u05D0\u05D5\u05E4\u05D9", description: "24 \u05D7\u05D5\u05D6\u05E7\u05D5\u05EA \u05D0\u05D5\u05E4\u05D9 \u05DE\u05D5\u05DB\u05D7\u05D5\u05EA \u05DE\u05D7\u05E7\u05E8\u05D9\u05EA." },
  { id: "schein", name: "\u05E2\u05D5\u05D2\u05E0\u05D9 \u05E7\u05E8\u05D9\u05D9\u05E8\u05D4 \u05E9\u05DC \u05E9\u05D9\u05D9\u05DF", description: "8 \u05E2\u05D5\u05D2\u05E0\u05D9 \u05DE\u05D5\u05D8\u05D9\u05D1\u05E6\u05D9\u05D4 \u05EA\u05E2\u05E1\u05D5\u05E7\u05EA\u05D9\u05D9\u05DD." },
  { id: "skills", name: "\u05DE\u05D9\u05E4\u05D5\u05D9 \u05DB\u05D9\u05E9\u05D5\u05E8\u05D9\u05DD", description: "\u05DB\u05D9\u05E9\u05D5\u05E8\u05D9\u05DD \u05E9\u05D0\u05E0\u05D9 \u05D9\u05D5\u05D3\u05E2/\u05E8\u05D5\u05E6\u05D4/\u05DE\u05D5\u05E7\u05D9\u05E8." },
  { id: "personality", name: "\u05D0\u05D1\u05D7\u05D5\u05DF \u05D0\u05D9\u05E9\u05D9\u05D5\u05EA", description: "\u05E4\u05E8\u05D5\u05E4\u05D9\u05DC \u05D0\u05D9\u05E9\u05D9\u05D5\u05EA\u05D9 \u05E4\u05E1\u05D9\u05DB\u05D5\u05DE\u05D8\u05E8\u05D9 \u05E7\u05E6\u05E8." },
  { id: "thinking", name: "\u05DB\u05D9\u05E9\u05D5\u05E8\u05D9 \u05D7\u05E9\u05D9\u05D1\u05D4", description: "\u05D1\u05D5\u05D7\u05DF \u05D7\u05E9\u05D9\u05D1\u05D4 \u05DE\u05D8\u05E8\u05D9\u05E6\u05D9\u05D5\u05E0\u05D9 \u05E7\u05E6\u05E8." },
  { id: "motivation", name: "\u05DE\u05D5\u05D8\u05D9\u05D1\u05E6\u05D9\u05D4 \u05D5\u05DE\u05D5\u05DB\u05E0\u05D5\u05EA", description: "\u05DE\u05D5\u05DB\u05E0\u05D5\u05EA \u05DE\u05E0\u05D8\u05DC\u05D9\u05EA \u05D5\u05E4\u05E8\u05D5\u05D0\u05E7\u05D8\u05D9\u05D1\u05D9\u05D5\u05EA." },
  { id: "values", name: "\u05E2\u05E8\u05DB\u05D9 \u05E2\u05D1\u05D5\u05D3\u05D4", description: "\u05DE\u05D9\u05E4\u05D5\u05D9 \u05E2\u05E8\u05DB\u05D9\u05DD \u05DC\u05EA\u05E2\u05E1\u05D5\u05E7\u05D4 \u05DE\u05E9\u05DE\u05E2\u05D5\u05EA\u05D9\u05EA." }
];
var list_assessments_default = defineTool({
  name: "list_assessments",
  title: "List assessments",
  description: "List the 8 self-discovery assessments available in the Sageify journey.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(ASSESSMENTS, null, 2) }],
    structuredContent: { assessments: ASSESSMENTS }
  })
});

// src/lib/mcp/tools/list-healthcare-tracks.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
var TRACKS = [
  {
    id: "pt",
    name: "\u05E4\u05D9\u05D6\u05D9\u05D5\u05EA\u05E8\u05E4\u05D9\u05D4",
    path: "/healthcare-sim/pt",
    description: "\u05D8\u05E4\u05DC \u05D1\u05DE\u05D8\u05D5\u05E4\u05DC\u05D9\u05DD \u05E2\u05DD \u05DB\u05D0\u05D1\u05D9 \u05D2\u05D1/\u05DB\u05EA\u05E3/\u05D1\u05E8\u05DA \u05D1\u05E8\u05E6\u05E3 \u05D4\u05E0\u05DB\u05D5\u05DF \u05E9\u05DC \u05D7\u05D9\u05DE\u05D5\u05DD, \u05D7\u05D9\u05D6\u05D5\u05E7 \u05D5\u05D0\u05E8\u05D2\u05D5\u05E0\u05D5\u05DE\u05D9\u05D4."
  },
  {
    id: "nutrition",
    name: "\u05EA\u05D6\u05D5\u05E0\u05D4 \u05E7\u05DC\u05D9\u05E0\u05D9\u05EA",
    path: "/healthcare-sim/nutrition",
    description: "\u05D1\u05E0\u05D4 \u05EA\u05D5\u05DB\u05E0\u05D9\u05D5\u05EA \u05D8\u05D9\u05E4\u05D5\u05DC \u05EA\u05D6\u05D5\u05E0\u05EA\u05D9 \u05DC\u05E1\u05D5\u05DB\u05E8\u05EA, \u05E2\u05D9\u05D9\u05E4\u05D5\u05EA \u05D5\u05DB\u05D5\u05DC\u05E1\u05D8\u05E8\u05D5\u05DC."
  },
  {
    id: "nursing-er",
    name: "\u05E1\u05D9\u05E2\u05D5\u05D3 \u2014 \u05DE\u05E9\u05DE\u05E8\u05EA \u05DE\u05D9\u05D5\u05DF",
    path: "/nursing-er",
    description: "\u05DE\u05E9\u05DE\u05E8\u05EA \u05DE\u05D9\u05D5\u05DF \u05E9\u05DC 90 \u05E9\u05E0\u05D9\u05D5\u05EA: \u05D1\u05D3\u05D5\u05E7 \u05E1\u05D9\u05DE\u05E0\u05D9\u05DD \u05D7\u05D9\u05D5\u05E0\u05D9\u05D9\u05DD, \u05D8\u05E4\u05DC, \u05D5\u05D0\u05DC \u05EA\u05E9\u05DB\u05D7 \u05DC\u05EA\u05E2\u05D3 \u05D5\u05DC\u05E9\u05D7\u05E8\u05E8."
  }
];
var list_healthcare_tracks_default = defineTool2({
  name: "list_healthcare_tracks",
  title: "List healthcare simulator tracks",
  description: "List the healthcare career simulator tracks in the Sageify app (for young audiences exploring health degrees).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => ({
    content: [{ type: "text", text: JSON.stringify(TRACKS, null, 2) }],
    structuredContent: { tracks: TRACKS }
  })
});

// src/lib/mcp/tools/get-app-info.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var get_app_info_default = defineTool3({
  name: "get_app_info",
  title: "About Sageify",
  description: "Get a short public description of the Sageify app: purpose, audience, and main journey.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const info = {
      name: "Sageify",
      tagline: "\u05D9\u05E0\u05E9\u05D5\u05E3 \u05D7\u05DB\u05DD. \u05DB\u05D9\u05D5\u05D5\u05DF \u05D0\u05DE\u05D9\u05EA\u05D9.",
      audience: "\u05D1\u05D5\u05D2\u05E8\u05D9\u05DD \u05D1\u05D2\u05D9\u05DC 60-80 \u05D4\u05DE\u05D7\u05E4\u05E9\u05D9\u05DD \u05DB\u05D9\u05D5\u05D5\u05DF \u05EA\u05E2\u05E1\u05D5\u05E7\u05EA\u05D9 \u05DE\u05E9\u05DE\u05E2\u05D5\u05EA\u05D9 \u05DC\u05E4\u05E8\u05E7 \u05D4\u05D7\u05D9\u05D9\u05DD \u05D4\u05D1\u05D0, \u05D5\u05DC\u05E6\u05D9\u05D3\u05DD \u05E1\u05D9\u05DE\u05D5\u05DC\u05D8\u05D5\u05E8 \u05D1\u05E8\u05D9\u05D0\u05D5\u05EA \u05DC\u05E7\u05D4\u05DC \u05E6\u05E2\u05D9\u05E8 \u05D4\u05E9\u05D5\u05E7\u05DC \u05EA\u05D5\u05D0\u05E8 \u05D1\u05DE\u05E7\u05E6\u05D5\u05E2\u05D5\u05EA \u05D4\u05D1\u05E8\u05D9\u05D0\u05D5\u05EA.",
      mentor: "\u05E1\u05D2\u05D9 \u2014 \u05D9\u05E0\u05E9\u05D5\u05E3 \u05DE\u05E0\u05D8\u05D5\u05E8 \u05DE\u05DC\u05D5\u05D5\u05D4 \u05D1\u05E9\u05D9\u05D7\u05D4 \u05D0\u05D9\u05E9\u05D9\u05EA \u05D5\u05D1\u05E0\u05D9\u05EA\u05D5\u05D7 \u05E4\u05E1\u05D9\u05DB\u05D5\u05DC\u05D5\u05D2\u05D9.",
      journey: "8 \u05E9\u05D0\u05DC\u05D5\u05E0\u05D9\u05DD \u05D7\u05D5\u05D5\u05D9\u05D9\u05EA\u05D9\u05D9\u05DD (\u05D4\u05D5\u05DC\u05E0\u05D3, VIA, \u05E9\u05D9\u05D9\u05DF, \u05D5\u05E2\u05D5\u05D3) \u2192 \u05E1\u05D9\u05DB\u05D5\u05DD \u05E4\u05E1\u05D9\u05DB\u05D5\u05DC\u05D5\u05D2\u05D9 \u2192 \u05E9\u05D9\u05D7\u05D4 \u05E2\u05DD \u05E1\u05D2\u05D9 \u2192 \u05EA\u05D5\u05DB\u05E0\u05D9\u05EA \u05D4\u05EA\u05E4\u05EA\u05D7\u05D5\u05EA \u05D0\u05D9\u05E9\u05D9\u05EA \u2192 \u05D0\u05E4\u05E9\u05E8\u05D5\u05EA \u05DC\u05E4\u05D2\u05D9\u05E9\u05EA \u05D9\u05D9\u05E2\u05D5\u05E5 \u05D0\u05E0\u05D5\u05E9\u05D9.",
      urls: {
        home: "https://sageify.life",
        demo: "https://sageify.life/#/demo-full",
        healthcareSim: "https://sageify.life/#/healthcare-sim"
      }
    };
    return {
      content: [{ type: "text", text: JSON.stringify(info, null, 2) }],
      structuredContent: info
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "sageify-mcp",
  title: "Sageify MCP",
  version: "0.1.0",
  instructions: "Public read-only tools that describe the Sageify career-discovery app: available assessments, healthcare simulator tracks, and general app info. No user or session data is exposed.",
  tools: [list_assessments_default, list_healthcare_tracks_default, get_app_info_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
